---
dist: trusty
sudo: required
language:
  - cpp
  - python
compiler:
  - gcc
python:
  - "2.7"
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval "${MATRIX_EVAL}"

cache:
  directories:
    - "~/.platformio"

install:
  - wget http://ftp.de.debian.org/debian/pool/main/l/lcov/lcov_1.13.orig.tar.gz
  - tar xf lcov_1.13.orig.tar.gz
  - make -C lcov-1.13 "PREFIX=${HOME}/.local" install
  - rm -rf lcov-1.13
  - pip install --user platformio
  - gem install coveralls-lcov
  - mkdir -p ~/.local/bin
  - wget -O ~/.local/bin/cpplint "$CPP_LINT_URL" && chmod 755 ~/.local/bin/cpplint

script:
  - PATH=~/.local/bin:$PATH
  - make lint
  - make ci
  - cd test && make clean test OPT=-O2
  - make clean coverage OPT=-O0
  - 'if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then coveralls-lcov --repo-token "$COVERALLS_TOKEN" coverage.info; fi'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then coveralls-lcov coverage.info; fi'

env:
  global:
    - CPP_LINT_URL=https://raw.githubusercontent.com/google/styleguide/gh-pages/cpplint/cpplint.py
    - secure: s5n3rtNF0ODwQY1f0ScuF4Hj1sElj3I3gdliHwCzWX4CQzJj7wX108l/GAXC+oohJlZ9OaFMEiNuHQj1Z5tzFxSS5YaB68h97HZ7+yIfh2pvhbSv09PlGUvfXiFRMzqMdT133JKXcsMwaDzdZNHBN/9E3tvNa61Fb2eVHQnCAQIh6w9UIo9ntyEtsQqcbZqtyOO1vry2sBf5JzhAA4LXwgTO7VfBKPFeFDnjozhPlxbMLJSNTgG9rGU2IPHLxs7WC+d8xRJMzISY6fJ5vbr7k3gDhxVyu89nj/w3dAEhWyzLY7qaRGTF0rLxA310anPQU+4QVSKndJFY0RpZcTPO2jexkMVnSi+n12sSPAp22CPtsJzO7tRmT+BCMZVTNg9CfPByPNgBvUcOi5hQOPXMbb97k4CX8+3NbVCTjxqlDzE1RjlIR27bXFtOuqfI7Q1YxVUZJbZlMKtAOtwOi5mZUU2x8zGsRQhPAYhPWYoudXn8K7OvpeONxO/wHw4c8AeZW59CVNuUvUsW67ZpFnPaGhkMDvFoVZfLuUUbLsllBYRdiz+QGExnRRE0wkkf8RvCi1dWgVd1MjxLuZNkuCHZ+4sNyMPsDZ6xEeJ0lSy5/p67Ap0VCkHU7d1Vy5jB5bY2kC5KPFTKahGBLwW7KUNaTRvq3QxYizQkGXoSeTGPEbU=
