name: 'Setup PlatformIO'
description: 'Install PlatformIO and required Python dependencies for embedded development'

inputs:
  install-lcov:
    description: 'Whether to install lcov for coverage reporting'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Install Python dependencies
      shell: bash
      run: |
        # zombie-imp and setuptools needed for compatibility for
        # some SDKs relying on older python versions (e.g. STM32)
        pip install platformio==6.1.18 zombie-imp==0.0.4 setuptools intelhex==2.3.0

    - name: Install lcov
      if: inputs.install-lcov == 'true'
      shell: bash
      run: |
        sudo apt-get update && sudo apt-get install -y lcov
