[env]
default_envs = nucleo_f401re

[env:nucleo_f401re]
platform = ststm32
framework = stm32cube
board = nucleo_f401re
board_build.stm32cube.custom_config_header = yes
lib_compat_mode = off
lib_deps = jandelgado/JLed@5.0.0

[platformio]
include_dir = Inc
src_dir = Src
